apiVersion: v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
        - name: app
          image: letaldiran/nodejsapp:latest
          ports:
            - containerPort: 9376
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: nginx-proxy
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp-service
spec:
  selector:
    app.kubernetes.io/name: nodejsapp
  type: NodePort

  ports:
    - protocol: TCP
      port: 80
      targetPort: nginx-proxy 
      nodePort: 9376